### ISSUE TITLE
Orientation seems incorrect in Frame or OrientationFunction

### ISSUE THREAD

**Issue by mmurooka** [jrl-umi3218/tvm#14]
The frame orientation generated by `OrientationFunction` task seems incorrect.

I implemented the sample code that solves the IK problem by TVM (based on [tests/RobotProblem.cpp](https://github.com/jrl-umi3218/tvm/blob/master/tests/RobotProblem.cpp)):
https://github.com/mmurooka/tmp_sources/tree/master/tvm_samples
The target position and orientation of the hand is updated by an interactive marker in the Rviz. However, the orientation of the hand is updated differently than the command with the interactive marker.
![tvm_ik_incorrect_rotation_20200706](https://user-images.githubusercontent.com/6636600/86567727-ccd1cf80-bfa6-11ea-926f-e575fc46b019.gif)
It's a little hard to see, but this issue can be easily reproduced with the source code of the above link.

I don't know yet about the cause of this issue. The pose markers of the target hand pose and actual hand pose match in the Rviz. So the OrientationFunction is satisfied correctly by the solver, and maybe there is a problem between Robot model and frame, and OrientationFunction.

**Comment by gergondet** [comment]
Hi @mmurooka 

Due to Featherstone's conventions you should [inverse the rotation provided by the marker](https://github.com/jrl-umi3218/mc_rtc_ros/blob/master/mc_rtc_rviz_panel/src/TransformInteractiveMarkerWidget.cpp#L58)

**Comment by mmurooka** [comment]
Fixed, thanks!
