### ISSUE TITLE
Using a different solver

### ISSUE THREAD

**Issue by BenjaminNavarro** [jrl-umi3218/tvm#2]
I wanted to test TVM myself but I don't have a copy of the LSSOL solver so I was wondering if it was possible to provide an interface for a different one (e.g QLD, QuadProg, OSQP, ...) ?

I tried to replace LSSOL with QuadProg but it seems that the two solvers use different parameters to represent the constraints. It's clearly out of my area of expertise so I would highly appreciate some help with that.

**Comment by aescande** [comment]
It is now possible to use QLD and Quadprog, and adding new solvers should be relatively easy.
