### ISSUE TITLE
Dependency on RBDyn and sch-core

### ISSUE THREAD

**Issue by stephane-caron** [jrl-umi3218/tvm#6]
Hi guys,

I'm considering numerical optimization libraries with higher-level features such as substitution and symbolic functions. TVM is a great candidate, but its dependency on RBDyn and sch-core is problematic.

Would you be able to make them optional rather than required?

**Comment by aescande** [comment]
Hi Stéphane,

that's actually something I'd like to do if @gergondet is ok with it.
It's about conditionally including the robot-related files and should be possible with minimal changes in CMake.
